export const FETCH_SOLAR_SYSTEMS_START = 'SOLAR/FETCH_SOLAR_SYSTEMS_START';
export const FETCH_SOLAR_SYSTEMS_SUCCESS = 'SOLAR/FETCH_SOLAR_SYSTEMS_SUCCESS';
export const FETCH_SOLAR_SYSTEMS_ERROR = 'SOLAR/FETCH_SOLAR_SYSTEMS_ERROR';
export const FETCH_SOLAR_SYSTEMS_DATA = 'SOLAR/FETCH_SOLAR_SYSTEMS_DATA';
export const GET_SOLAR_SYSTEM_DATA = 'SOLAR/GET_SOLAR_SYSTEM_DATA';
export const ERROR_MESSAGE = 'error';
